import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Forte Global",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/forte-logo.png" type="image/png" />
      <head></head>
      <body>
        <div>
          <div className="bg-body-gradient w-screen h-screen fixed top-0 left-0 z-[-1]"></div>
          <div className="p-4 md:px-[50px] xl:px-[66px] min-h-screen max-w-[1440px] mx-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
