export const stripeCurrencies = [
  {
    value: "AED",
    name: "United Arab Emirates Dirham",
    symbol: "د.إ",
    flag: "🇦🇪",
  },
  { value: "AFN", name: "Afghan Afghani", symbol: "؋", flag: "🇦🇫" },
  { value: "ALL", name: "Albanian Lek", symbol: "L", flag: "🇦🇱" },
  { value: "AMD", name: "Armenian Dram", symbol: "֏", flag: "🇦🇲" },
  {
    value: "ANG",
    name: "Netherlands Antillean Guilder",
    symbol: "ƒ",
    flag: "🇳🇱",
  },
  { value: "AOA", name: "Angolan Kwanza", symbol: "Kz", flag: "🇦🇴" },
  { value: "ARS", name: "Argentine Peso", symbol: "$", flag: "🇦🇷" },
  { value: "AUD", name: "Australian Dollar", symbol: "A$", flag: "🇦🇺" },
  { value: "AWG", name: "Aruban Florin", symbol: "ƒ", flag: "🇦🇼" },
  { value: "AZN", name: "Azerbaijani Manat", symbol: "₼", flag: "🇦🇿" },
  {
    value: "BAM",
    name: "Bosnia & Herzegovina Convertible Mark",
    symbol: "KM",
    flag: "🇧🇦",
  },
  { value: "BBD", name: "Barbadian Dollar", symbol: "Bds$", flag: "🇧🇧" },
  { value: "BDT", name: "Bangladeshi Taka", symbol: "৳", flag: "🇧🇩" },
  { value: "BGN", name: "Bulgarian Lev", symbol: "лв", flag: "🇧🇬" },
  { value: "BIF", name: "Burundian Franc", symbol: "FBu", flag: "🇧🇮" },
  { value: "BMD", name: "Bermudan Dollar", symbol: "BD$", flag: "🇧🇲" },
  { value: "BND", name: "Brunei Dollar", symbol: "B$", flag: "🇧🇳" },
  { value: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", flag: "🇧🇴" },
  { value: "BRL", name: "Brazilian Real", symbol: "R$", flag: "🇧🇷" },
  { value: "BSD", name: "Bahamian Dollar", symbol: "B$", flag: "🇧🇸" },
  { value: "BWP", name: "Botswanan Pula", symbol: "P", flag: "🇧🇼" },
  { value: "BYN", name: "Belarusian Ruble", symbol: "Br", flag: "🇧🇾" },
  { value: "BZD", name: "Belize Dollar", symbol: "BZ$", flag: "🇧🇿" },
  { value: "CAD", name: "Canadian Dollar", symbol: "C$", flag: "🇨🇦" },
  { value: "CDF", name: "Congolese Franc", symbol: "FC", flag: "🇨🇩" },
  { value: "CHF", name: "Swiss Franc", symbol: "CHF", flag: "🇨🇭" },
  { value: "CLP", name: "Chilean Peso", symbol: "$", flag: "🇨🇱" },
  { value: "CNY", name: "Chinese Yuan", symbol: "¥", flag: "🇨🇳" },
  { value: "COP", name: "Colombian Peso", symbol: "$", flag: "🇨🇴" },
  { value: "CRC", name: "Costa Rican Colón", symbol: "₡", flag: "🇨🇷" },
  { value: "CVE", name: "Cape Verdean Escudo", symbol: "$", flag: "🇨🇻" },
  { value: "CZK", name: "Czech Koruna", symbol: "Kč", flag: "🇨🇿" },
  { value: "DJF", name: "Djiboutian Franc", symbol: "Fdj", flag: "🇩🇯" },
  { value: "DKK", name: "Danish Krone", symbol: "kr", flag: "🇩🇰" },
  { value: "DOP", name: "Dominican Peso", symbol: "RD$", flag: "🇩🇴" },
  { value: "DZD", name: "Algerian Dinar", symbol: "د.ج", flag: "🇩🇿" },
  { value: "EGP", name: "Egyptian Pound", symbol: "E£", flag: "🇪🇬" },
  { value: "ETB", name: "Ethiopian Birr", symbol: "Br", flag: "🇪🇹" },
  { value: "EUR", name: "Euro", symbol: "€", flag: "🇪🇺" },
  { value: "FJD", name: "Fijian Dollar", symbol: "FJ$", flag: "🇫🇯" },
  { value: "FKP", name: "Falkland Islands Pound", symbol: "£", flag: "🇫🇰" },
  { value: "GBP", name: "British Pound", symbol: "£", flag: "🇬🇧" },
  { value: "GEL", name: "Georgian Lari", symbol: "₾", flag: "🇬🇪" },
  { value: "GHS", name: "Ghanaian Cedi", symbol: "GH₵", flag: "🇬🇭" },
  { value: "GIP", name: "Gibraltar Pound", symbol: "£", flag: "🇬🇮" },
  { value: "GMD", name: "Gambian Dalasi", symbol: "D", flag: "🇬🇲" },
  { value: "GNF", name: "Guinean Franc", symbol: "FG", flag: "🇬🇳" },
  { value: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", flag: "🇬🇹" },
  { value: "GYD", name: "Guyanaese Dollar", symbol: "G$", flag: "🇬🇾" },
  { value: "HKD", name: "Hong Kong Dollar", symbol: "HK$", flag: "🇭🇰" },
  { value: "HNL", name: "Honduran Lempira", symbol: "L", flag: "🇭🇳" },
  { value: "HRK", name: "Croatian Kuna", symbol: "kn", flag: "🇭🇷" },
  { value: "HTG", name: "Haitian Gourde", symbol: "G", flag: "🇭🇹" },
  { value: "HUF", name: "Hungarian Forint", symbol: "Ft", flag: "🇭🇺" },
  { value: "IDR", name: "Indonesian Rupiah", symbol: "Rp", flag: "🇮🇩" },
  { value: "ILS", name: "Israeli New Shekel", symbol: "₪", flag: "🇮🇱" },
  { value: "INR", name: "Indian Rupee", symbol: "₹", flag: "🇮🇳" },
  { value: "ISK", name: "Icelandic Króna", symbol: "kr", flag: "🇮🇸" },
  { value: "JMD", name: "Jamaican Dollar", symbol: "J$", flag: "🇯🇲" },
  { value: "JPY", name: "Japanese Yen", symbol: "¥", flag: "🇯🇵" },
  { value: "KES", name: "Kenyan Shilling", symbol: "KSh", flag: "🇰🇪" },
  { value: "KGS", name: "Kyrgystani Som", symbol: "с", flag: "🇰🇬" },
  { value: "KHR", name: "Cambodian Riel", symbol: "៛", flag: "🇰🇭" },
  { value: "KMF", name: "Comorian Franc", symbol: "CF", flag: "🇰🇲" },
  { value: "KRW", name: "South Korean Won", symbol: "₩", flag: "🇰🇷" },
  { value: "KYD", name: "Cayman Islands Dollar", symbol: "CI$", flag: "🇰🇾" },
  { value: "KZT", name: "Kazakhstani Tenge", symbol: "₸", flag: "🇰🇿" },
  { value: "LAK", name: "Laotian Kip", symbol: "₭", flag: "🇱🇦" },
  { value: "LBP", name: "Lebanese Pound", symbol: "ل.ل", flag: "🇱🇧" },
  { value: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", flag: "🇱🇰" },
  { value: "LRD", name: "Liberian Dollar", symbol: "L$", flag: "🇱🇷" },
  { value: "LSL", name: "Lesotho Loti", symbol: "M", flag: "🇱🇸" },
  { value: "MAD", name: "Moroccan Dirham", symbol: "د.م.", flag: "🇲🇦" },
  { value: "MDL", name: "Moldovan Leu", symbol: "L", flag: "🇲🇩" },
  { value: "MGA", name: "Malagasy Ariary", symbol: "Ar", flag: "🇲🇬" },
  { value: "MKD", name: "Macedonian Denar", symbol: "ден", flag: "🇲🇰" },
  { value: "MMK", name: "Myanmar Kyat", symbol: "K", flag: "🇲🇲" },
  { value: "MNT", name: "Mongolian Tugrik", symbol: "₮", flag: "🇲🇳" },
  { value: "MOP", name: "Macanese Pataca", symbol: "MOP$", flag: "🇲🇴" },
  { value: "MRO", name: "Mauritanian Ouguiya", symbol: "UM", flag: "🇲🇷" },
  { value: "MUR", name: "Mauritian Rupee", symbol: "₨", flag: "🇲🇺" },
  { value: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", flag: "🇲🇻" },
  { value: "MWK", name: "Malawian Kwacha", symbol: "MK", flag: "🇲🇼" },
  { value: "MXN", name: "Mexican Peso", symbol: "MX$", flag: "🇲🇽" },
  { value: "MYR", name: "Malaysian Ringgit", symbol: "RM", flag: "🇲🇾" },
  { value: "MZN", name: "Mozambican Metical", symbol: "MT", flag: "🇲🇿" },
  { value: "NAD", name: "Namibian Dollar", symbol: "N$", flag: "🇳🇦" },
  { value: "NGN", name: "Nigerian Naira", symbol: "₦", flag: "🇳🇬" },
  { value: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", flag: "🇳🇮" },
  { value: "NOK", name: "Norwegian Krone", symbol: "kr", flag: "🇳🇴" },
  { value: "NPR", name: "Nepalese Rupee", symbol: "₨", flag: "🇳🇵" },
  { value: "NZD", name: "New Zealand Dollar", symbol: "NZ$", flag: "🇳🇿" },
  { value: "PAB", name: "Panamanian Balboa", symbol: "B/.", flag: "🇵🇦" },
  { value: "PEN", name: "Peruvian Nuevo Sol", symbol: "S/.", flag: "🇵🇪" },
  { value: "PGK", name: "Papua New Guinean Kina", symbol: "K", flag: "🇵🇬" },
  { value: "PHP", name: "Philippine Peso", symbol: "₱", flag: "🇵🇭" },
  { value: "PKR", name: "Pakistani Rupee", symbol: "₨", flag: "🇵🇰" },
  { value: "PLN", name: "Polish Złoty", symbol: "zł", flag: "🇵🇱" },
  { value: "PYG", name: "Paraguayan Guarani", symbol: "₲", flag: "🇵🇾" },
  { value: "QAR", name: "Qatari Rial", symbol: "ر.ق", flag: "🇶🇦" },
  { value: "RON", name: "Romanian Leu", symbol: "lei", flag: "🇷🇴" },
  { value: "RSD", name: "Serbian Dinar", symbol: "дин.", flag: "🇷🇸" },
  { value: "RUB", name: "Russian Ruble", symbol: "₽", flag: "🇷🇺" },
  { value: "RWF", name: "Rwandan Franc", symbol: "RF", flag: "🇷🇼" },
  { value: "SAR", name: "Saudi Riyal", symbol: "ر.س", flag: "🇸🇦" },
  { value: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", flag: "🇸🇧" },
  { value: "SCR", name: "Seychellois Rupee", symbol: "SR", flag: "🇸🇨" },
  { value: "SEK", name: "Swedish Krona", symbol: "kr", flag: "🇸🇪" },
  { value: "SGD", name: "Singapore Dollar", symbol: "S$", flag: "🇸🇬" },
  { value: "SHP", name: "Saint Helena Pound", symbol: "£", flag: "🇸🇭" },
  { value: "SLL", name: "Sierra Leonean Leone", symbol: "Le", flag: "🇸🇱" },
  { value: "SOS", name: "Somali Shilling", symbol: "S", flag: "🇸🇴" },
  { value: "SRD", name: "Surinamese Dollar", symbol: "$", flag: "🇸🇷" },
  { value: "STD", name: "São Tomé & Príncipe Dobra", symbol: "Db", flag: "🇸🇹" },
  { value: "SVC", name: "Salvadoran Colón", symbol: "₡", flag: "🇸🇻" },
  { value: "SZL", name: "Swazi Lilangeni", symbol: "L", flag: "🇸🇿" },
  { value: "THB", name: "Thai Baht", symbol: "฿", flag: "🇹🇭" },
  { value: "TJS", name: "Tajikistani Somoni", symbol: "ЅМ", flag: "🇹🇯" },
  { value: "TOP", name: "Tongan Paʻanga", symbol: "T$", flag: "🇹🇴" },
  { value: "TRY", name: "Turkish Lira", symbol: "₺", flag: "🇹🇷" },
  { value: "TTD", name: "Trinidad & Tobago Dollar", symbol: "TT$", flag: "🇹🇹" },
  { value: "TWD", name: "New Taiwan Dollar", symbol: "NT$", flag: "🇹🇼" },
  { value: "TZS", name: "Tanzanian Shilling", symbol: "TSh", flag: "🇹🇿" },
  { value: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", flag: "🇺🇦" },
  { value: "UGX", name: "Ugandan Shilling", symbol: "USh", flag: "🇺🇬" },
  { value: "USD", name: "US Dollar", symbol: "$", flag: "🇺🇸" },
  { value: "UYU", name: "Uruguayan Peso", symbol: "$U", flag: "🇺🇾" },
  { value: "UZS", name: "Uzbekistani Som", symbol: "лв", flag: "🇺🇿" },
  { value: "VEF", name: "Venezuelan Bolívar", symbol: "Bs", flag: "🇻🇪" },
  { value: "VND", name: "Vietnamese Đồng", symbol: "₫", flag: "🇻🇳" },
  { value: "VUV", name: "Vanuatu Vatu", symbol: "VT", flag: "🇻🇺" },
  { value: "WST", name: "Samoan Tala", symbol: "WS$", flag: "🇼🇸" },
  {
    value: "XAF",
    name: "Central African CFA Franc",
    symbol: "FCFA",
    flag: "🇨🇲",
  },
  { value: "XCD", name: "East Caribbean Dollar", symbol: "EC$", flag: "🇦🇮" },
  { value: "XOF", name: "West African CFA Franc", symbol: "CFA", flag: "🇧🇯" },
  { value: "XPF", name: "CFP Franc", symbol: "₣", flag: "🇵🇫" },
  { value: "YER", name: "Yemeni Rial", symbol: "﷼", flag: "🇾🇪" },
  { value: "ZAR", name: "South African Rand", symbol: "R", flag: "🇿🇦" },
  { value: "ZMW", name: "Zambian Kwacha", symbol: "ZK", flag: "🇿🇲" },
];

// Map to Dropdown options
const currencies = stripeCurrencies.map((c) => ({
  value: c.value,
  label: `${c.name} (${c.symbol})`,
}));

export default currencies;
