name: Build and Deploy NextJS App to S3 and CloudFront

on:
  push:
    branches:
      - development

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build

      - name: Build project
        run: yarn run export

      - name: List directory contents
        run: pwd; ls -l

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync $GITHUB_WORKSPACE/out s3://${{ secrets.S3_BUCKET_NAME }} --region ${{ secrets.AWS_REGION }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
