name: Build and Deploy to ECS

on:
  push:
    branches: ["development"]

env:
  AWS_REGION: "ap-southeast-2"
  ECR_REPOSITORY: "frontend"
  CLUSTER_NAME: "forte-dev"
  SERVICE_NAME: "dev-forte-frontend-svc"
  TASKDEF_NAME: "dev-forte-frontend"

jobs:
  build:
    name: clone, build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and push it to ECR so that it can be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Create new revision and deploy to ECS
        run: |
          sudo apt-get install jq -y
          jq --version
          # Fetch the current task definition and modify it for the new image
          aws ecs describe-task-definition --task-definition ${{ env.TASKDEF_NAME }} > task-def.json

          # Prepare the new task definition with updated container image
          jq --arg IMAGE "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" \
            '.taskDefinition | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) | .containerDefinitions[0].image = $IMAGE' task-def.json > new-task-def.json

          # Register the new task definition
          aws ecs register-task-definition --cli-input-json file://new-task-def.json

          # Update the ECS service with the new task definition
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME }} --force-new-deployment
        shell: bash
