name: Build and Deploy to ECS for testing

on:
  push:
    branches: ["production"]

env:
  AWS_REGION: "ap-southeast-2"
  ECR_REPOSITORY: "frontend"
  CLUSTER_NAME: "forte-prod"
  SERVICE_NAME: "prod-forte-frontend-svc"
  TASKDEF_NAME: "prod-forte-frontend"

jobs:
  build:
    name: clone, build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and push it to ECR so that it can be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: create new revision and deploy to ECS
        run: |
          sudo apt-get install jq -y
          jq --version
          aws ecs describe-task-definition --task-definition ${{ env.TASKDEF_NAME }} > task-def.json
          jq .taskDefinition task-def.json > taskdefinition.json
          jq 'del(.taskDefinitionArn)' taskdefinition.json | jq 'del(.revision)' | jq 'del(.status)' | jq 'del(.requiresAttributes)' | jq 'del(.compatibilities)' | jq 'del(.registeredAt)' | jq 'del(.registeredBy)' > container-definition.json
          aws ecs register-task-definition --cli-input-json file://container-definition.json
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME }} --task-definition ${{ env.TASKDEF_NAME }}
        shell: bash
